# Add 'test' label to any change to *.spec.js files within the source dir
tests:
  - tests/**/*Test.php
  - ./phpunit.xml
  - ./.travis.yml

CS:
  - ./.styleci.yml
  - ./.editorconfig

dependencies:
  - ./composer.*
  - ./package*.json

javascript:
  - .js
  - .vue

Localization: resources/lang/*

database: database/*

UI: resources/views/*

admin: app/Nova/*


config:
  - config/*
  - .env.example

# Add 'repo' label to files that affect only the GitHub Repository
repo:
  - .gitignore
  - .gitattribute
  - .github/*
  - ./README.md
